# Generated by Django 3.0 on 2020-11-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfoliowebapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
