# Generated by Django 3.0 on 2020-11-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfoliowebapp', '0003_playlist_tutorials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
