# Generated by Django 3.0 on 2020-11-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protfoliowebapp', '0006_auto_20201124_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_header', models.CharField(max_length=1000)),
                ('video_url', models.URLField(max_length=1000)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_header', models.CharField(max_length=1000)),
                ('video_url', models.URLField(max_length=1000)),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfoliowebapp.Tutorials'),
        ),
    ]
