# Generated by Django 3.0 on 2020-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfoliowebapp', '0007_auto_20201124_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidePanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('details', models.TextField()),
            ],
        ),
    ]
